export const travel = [
    {
        id: '1',
        img: '../../assets/img/pic-1.jpg',
        destination: 'B&B Hotel Albacete',
        discription: 'B&B Hotel Albacete is 3 km from the centre of Albacete, next to Imaginalia Shopping Centre and the A32 Motorway. It offers free Wi-Fi, free parking and a 24-hour reception. Modern, air-conditioned rooms have a flat-screen TV and work desk. They are also heated and feature a private bathroom with a rain-effect shower. Guests can enjoy a continental breakfast at the B&B Hotel Albacete. The hotel is just 8 km from the Albacete Speed Racing Circuit, and next to the city’s main business park. We speak your language!',
        start: '10.08.2021',
        duration: '7 Days',
        price: '159',
    },
    {
        id: '2',
        img: '../../assets/img/Pic-2.jpg',
        destination: 'Hotel Castilla',
        discription: 'Hotel Castilla is located in the centre of Albacete, 300 m from the city’s Knife Museum. It offers 24-hour room service and free Wi-Fi throughout the hotel.All rooms at the Castilla have both air conditioning and heating, and a flat-screen TV. Some feature views of the Parque Líneal.Castilla Hotel has a café where you can buy drinks and snacks, and it also has a meeting room and a garage.The hotel is located just 3 minutes’ walk from the train and bus stations. Albacete bullring is a 10-minute walk away and the main square is 400 m away from the Hotel Castilla.',
        start: '05.07.2021',
        duration: '14 Days',
        price: '210',
    },
    {
        id: '3',
        img: '../../assets/img/pic-3.jpg',
        destination: 'Beatriz Albacete',
        discription: 'Beatriz Albacete has a convenient location close to the Palacio de Congresos Conference Centre and major transport links. It offers an extensive, modern spa and fitness centre. The Beatriz Albacete offers large, well-designed rooms, with full soundproofing and air conditioning, ideal for rest and relaxation after a tiring day. Enjoy the buffet breakfast, as well as lunch and dinner at the restaurant, or have a drink at the bar. This hotel also has a 24-hour reception desk, allowing you to arrive in the early hours.',
        start: '1.06.2021',
        duration: '4 Days',
        price: '96',
    },
    {
        id: '4',
        img: '../../assets/img/pic-4.jpg',
        destination: 'Hotel Florida',
        discription: 'Hotel Florida is conveniently located in the centre of Albacete, next to the Bullring and 600 m from the Fair of Albacete. It offers a restaurant and rooms with free Wi-Fi. Located 5 minutes’ walk from the city centre, the Florida hotel has several meeting and banquet rooms and a discotheque. Laundry and ironing services can be requested for an extra cost. Rooms have air conditioning and heating, featuring parquet floors, a mini fridge and a TV. The private bathrooms come with hairdryer and free toiletries. The restaurant serves homemade meals and specialises in rice, Mediterranean and local cuisine. Á la carte dishes and set menus are available. The cafeteria offers a selection of tapas and snacks, as well as packed lunches. Private parking is possible at an extra cost. Albacete Airport is 15 minutes’ drive away.',
        start: '30.08.2021',
        duration: '7 Days',
        price: '174',
    },
    {
        id: '5',
        img: '../../assets/img/pic-5.jpg',
        destination: 'Hotel Europa',
        discription: 'This smart, city-centre hotel provides an elegant setting for your visit to Albacete and the surrounding region of La Mancha. The Europa’s central location means that you can easily walk to the sights of the city centre, including San Juan Cathedral, Plaza Mayor and the City Museum. Albacete’s congress centre is also just 3 km away. Business guests can make use of the free Wi-Fi internet service. There is also a function room which can hold up to 800 guests.',
        start: '26.08.2021',
        duration: '9 Days',
        price: '110',
    },
    {
        id: '6',
        img: '../../assets/img/pic-6.jpg',
        destination: 'Hotel Universidad',
        discription: 'Set next to the University of Castilla la Mancha, Hotel Universidad is in a quiet residential area of Albacete. Rooms include a minibar, flat-screen TV and free Wi-Fi access. The Universidad Hotel offers stylish, functional design, with spacious lounges and public areas. There is also a bar with a terrace. The 24-hour reception can arrange car rental. Rooms at the Universidad are decorated in soft, neutral colours. All rooms include air conditioning, heating and a private bathroom with a hairdryer and toiletries. The hotel is less than 2 km from Albacete’s historic city centre. El Corte Inglés Department Store and the Carlos Belmonte Football Stadium are 300 m away.',
        start: '09.09.2021',
        duration: '5 Days',
        price: '315',
    },
]